# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):

    # 초기화: 해당 창의 크기(가로, 세로) 설정
    def __init__(self, width, height):
        self.__width = width
        self.__height = height

    def setupUi(self, Form):
        Form.setObjectName("Title Preview")
        Form.setFixedSize(self.__width, self.__height)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        Form.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 70, 781, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titleText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.titleText.setObjectName("titleText")
        self.horizontalLayout_4.addWidget(self.titleText)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.templateSelector = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.templateSelector.setObjectName("templateSelector")
        self.horizontalLayout_6.addWidget(self.templateSelector)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.startTimeText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.startTimeText.setObjectName("startTimeText")
        self.gridLayout.addWidget(self.startTimeText, 1, 2, 1, 1)
        self.endTimeText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.endTimeText.setObjectName("endTimeText")
        self.gridLayout.addWidget(self.endTimeText, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.previewImageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.previewImageLabel.setObjectName("previewImageLabel")
        self.horizontalLayout.addWidget(self.previewImageLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Title Preview"))
        self.label_3.setText(_translate("Form", "끝"))
        self.label_2.setText(_translate("Form", "시작"))
        self.label_5.setText(_translate("Form", "자막 템플릿"))
        self.label_4.setText(_translate("Form", "자막 텍스트"))
        self.previewImageLabel.setText(_translate("Form", "Preview Image (Alternative Text)"))


# 메인함수 실행
def main() -> int:
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    preview_ui = Ui_Form(900, 400)
    preview_ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

    return 0

# 이 코드가 처음으로 실행될 경우 메인함수 실행
if __name__ == '__main__':
    print("program exited with code", main())
    
